### PR TITLE
Refactor to MirageJS

### PR DESCRIPTION
**Pull request by minkimcello**
## Motivation
Screen Shot 2020-07-14 at 4 57 15 PM
This is part of an on-going initiative to completely migrate all of `folio-org` projects from `@bigtest/mirage` to `miragejs`.

[`@bigtest/mirage`](https://github.com/bigtestjs/mirage/) was originally a prototype to make `mirage` available to any framework, but it has since been archived in favor of [`miragejs`](https://miragejs.com/). The documentation for `miragejs` is not only prodigious for its extensive API docs but also for its tutorials and guides. Furthermore, it receives regular bug-fixes and maintenance releases in thanks to its extremely large and active community.

Previous PR: [@folio-org/ui-erm-usage #212](https://github.com/folio-org/ui-erm-usage/pull/212)
_Linking the previous pull request so that subsequent ones can be found tagged below._

<details>
<summary>Overview of progress at the time of the creation of this PR (in chronological order):</summary>
<br>
✅ <code>ui-checkin</code>
<br>
✅ <code>ui-checkout</code>
<br>
☑️ <code>ui-circulation</code>
<br>
☑️ <code>ui-calendar</code>
<br>
✅ <code>ui-agreements</code>
<br>
☑️ <code>ui-app-template</code>
<br>
☑️ <code>ui-inventory</code>
<br>
☑️ <code>ui-data-export</code>
<br>
✅ <code>ui-finc-config</code>
<br>
☑️ <code>ui-licenses</code>
<br>
☑️ <code>ui-erm-comparisons</code>
<br>
☑️ <code>ui-myprofile</code>
<br>
☑️ <code>ui-local-kb-admin</code>
<br>
☑️ <code>ui-marccat</code>
<br>
☑️ <code>ui-finc-select</code>
<br>
☑️ <code>ui-erm-usage</code>
<br>
☑️ <code>ui-notes</code>
</details>

## Approach
- [x] Removed `@bigtest/mirage` and added `inflected` and `miragejs`.
- [x] ESlint and ~ran tests~ ⚠️ There were no tests to run.

### CODE REVIEW

**Comment by BogdanDenis** [comment]
Hey @minkimcello and @zburke, this PR looks good to me and I think it can be merged. Only question is that one Jenkins check hasn't passed and I can't see the branch (possibly because this is a PR from a fork?)
Have you had this happen before?

**Comment by minkimcello** [comment]
@BogdanDenis we also have a stalling check in `ui-app-template` too. it's been like this for a week. 🤷‍♂️. maybe it's a jenkins configuration issue? i would assume `continuous-integration/jenkins/pr-merge` passing is sufficient?

**Comment by BogdanDenis** [comment]
@minkimcello maybe it is... let me ask DevOps about it

**Comment by dcrossleyau** [comment]
I now re-configured the Settings to be the same Required checks as other repos, i.e. only requires "pr-merge" and "cla".

**Pull request merged**
